// Printer + filament presets. Build volumes are in mm (X x Y x Z where Z is height).
// Sources: manufacturer spec sheets, public OrcaSlicer / PrusaSlicer profile data.

export const PRINTERS = [
  {
    id: "custom",
    brand: "Custom",
    name: "Custom / Generic",
    buildVolume: { x: 220, y: 220, z: 250 },
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 60,
  },
  {
    id: "bambu-p1s",
    brand: "Bambu Lab",
    name: "P1S",
    buildVolume: { x: 256, y: 256, z: 256 },
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 200,
  },
  {
    id: "bambu-a1",
    brand: "Bambu Lab",
    name: "A1",
    buildVolume: { x: 256, y: 256, z: 256 },
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 180,
  },
  {
    id: "bambu-a1-mini",
    brand: "Bambu Lab",
    name: "A1 mini",
    buildVolume: { x: 180, y: 180, z: 180 },
    maxNozzleTemp: 300,
    maxBedTemp: 80,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 180,
  },
  {
    id: "bambu-x1c",
    brand: "Bambu Lab",
    name: "X1 Carbon",
    buildVolume: { x: 256, y: 256, z: 256 },
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 200,
  },
  {
    id: "prusa-mk4",
    brand: "Prusa",
    name: "MK4 / MK4S",
    buildVolume: { x: 250, y: 210, z: 220 },
    maxNozzleTemp: 290,
    maxBedTemp: 120,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 150,
  },
  {
    id: "prusa-mini",
    brand: "Prusa",
    name: "MINI / MINI+",
    buildVolume: { x: 180, y: 180, z: 180 },
    maxNozzleTemp: 280,
    maxBedTemp: 100,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 120,
  },
  {
    id: "prusa-xl",
    brand: "Prusa",
    name: "XL",
    buildVolume: { x: 360, y: 360, z: 360 },
    maxNozzleTemp: 290,
    maxBedTemp: 120,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 200,
  },
  {
    id: "creality-ender3-v3-se",
    brand: "Creality",
    name: "Ender-3 V3 SE",
    buildVolume: { x: 220, y: 220, z: 250 },
    maxNozzleTemp: 260,
    maxBedTemp: 100,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 100,
  },
  {
    id: "creality-ender3-pro",
    brand: "Creality",
    name: "Ender-3 / Pro",
    buildVolume: { x: 220, y: 220, z: 250 },
    maxNozzleTemp: 250,
    maxBedTemp: 100,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 60,
  },
  {
    id: "creality-k1",
    brand: "Creality",
    name: "K1 / K1 Max",
    buildVolume: { x: 220, y: 220, z: 250 },
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 250,
  },
  {
    id: "flashforge-adventurer5m",
    brand: "FlashForge",
    name: "Adventurer 5M / 5M Pro",
    buildVolume: { x: 220, y: 220, z: 220 },
    maxNozzleTemp: 280,
    maxBedTemp: 110,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 200,
  },
  {
    id: "flashforge-ad5x",
    brand: "FlashForge",
    name: "AD5X (Adventurer 5X)",
    buildVolume: { x: 220, y: 220, z: 220 },
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 600,
  },
  {
    id: "flashforge-creator5",
    brand: "FlashForge",
    name: "Creator 5 (IDEX)",
    buildVolume: { x: 300, y: 250, z: 200 },
    maxNozzleTemp: 320,
    maxBedTemp: 120,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 200,
  },
  {
    id: "flashforge-creator5-pro",
    brand: "FlashForge",
    name: "Creator 5 Pro (IDEX)",
    buildVolume: { x: 300, y: 250, z: 200 },
    maxNozzleTemp: 320,
    maxBedTemp: 120,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 200,
  },
  {
    id: "flashforge-creator-pro",
    brand: "FlashForge",
    name: "Creator Pro 2",
    buildVolume: { x: 200, y: 148, z: 150 },
    maxNozzleTemp: 240,
    maxBedTemp: 120,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 60,
  },
  {
    id: "flashforge-finder",
    brand: "FlashForge",
    name: "Finder",
    buildVolume: { x: 140, y: 140, z: 140 },
    maxNozzleTemp: 240,
    maxBedTemp: 0,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 60,
  },
  {
    id: "elegoo-neptune-4",
    brand: "Elegoo",
    name: "Neptune 4",
    buildVolume: { x: 225, y: 225, z: 265 },
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 250,
  },
  {
    id: "elegoo-neptune-4-pro",
    brand: "Elegoo",
    name: "Neptune 4 Pro",
    buildVolume: { x: 225, y: 225, z: 265 },
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 500,
  },
  {
    id: "elegoo-neptune-4-plus",
    brand: "Elegoo",
    name: "Neptune 4 Plus",
    buildVolume: { x: 320, y: 320, z: 385 },
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 500,
  },
  {
    id: "elegoo-neptune-4-max",
    brand: "Elegoo",
    name: "Neptune 4 Max",
    buildVolume: { x: 420, y: 420, z: 480 },
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 500,
  },
  {
    id: "elegoo-neptune-3",
    brand: "Elegoo",
    name: "Neptune 3 / Plus / Pro / Max",
    buildVolume: { x: 220, y: 220, z: 280 },
    maxNozzleTemp: 260,
    maxBedTemp: 110,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 150,
  },
  {
    id: "elegoo-centauri-carbon",
    brand: "Elegoo",
    name: "Centauri Carbon",
    buildVolume: { x: 256, y: 256, z: 256 },
    maxNozzleTemp: 320,
    maxBedTemp: 110,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 500,
  },
  {
    id: "elegoo-orangestorm-giga",
    brand: "Elegoo",
    name: "OrangeStorm Giga",
    buildVolume: { x: 800, y: 800, z: 1000 },
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 200,
  },
  {
    id: "anycubic-kobra2",
    brand: "Anycubic",
    name: "Kobra 2 / Pro / Plus",
    buildVolume: { x: 220, y: 220, z: 250 },
    maxNozzleTemp: 260,
    maxBedTemp: 110,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 150,
  },
  {
    id: "sovol-sv06",
    brand: "Sovol",
    name: "SV06 / SV06 Plus",
    buildVolume: { x: 220, y: 220, z: 250 },
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 100,
  },
  {
    id: "sovol-sv07",
    brand: "Sovol",
    name: "SV07 / SV07 Plus",
    buildVolume: { x: 235, y: 235, z: 300 },
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 250,
  },
  {
    id: "sovol-sv08",
    brand: "Sovol",
    name: "SV08",
    buildVolume: { x: 350, y: 350, z: 345 },
    maxNozzleTemp: 300,
    maxBedTemp: 120,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 500,
  },
  {
    id: "voron-2.4",
    brand: "Voron",
    name: "Voron 2.4 (300mm)",
    buildVolume: { x: 300, y: 300, z: 300 },
    maxNozzleTemp: 300,
    maxBedTemp: 120,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 200,
  },
];

export const FILAMENTS = [
  {
    id: "pla",
    name: "PLA",
    nozzleTemp: 210,
    bedTemp: 60,
    minNozzleTemp: 190,
    maxNozzleTemp: 230,
    minBedTemp: 0,
    maxBedTemp: 70,
    printSpeedMultiplier: 1.0,
    retraction: 1.0,
    notes: "Easy. Great for prototyping. No enclosure needed.",
  },
  {
    id: "pla-plus",
    name: "PLA+",
    nozzleTemp: 215,
    bedTemp: 60,
    minNozzleTemp: 200,
    maxNozzleTemp: 235,
    minBedTemp: 0,
    maxBedTemp: 70,
    printSpeedMultiplier: 1.0,
    retraction: 1.0,
    notes: "Tougher than PLA, same workflow.",
  },
  {
    id: "petg",
    name: "PETG",
    nozzleTemp: 240,
    bedTemp: 80,
    minNozzleTemp: 220,
    maxNozzleTemp: 260,
    minBedTemp: 70,
    maxBedTemp: 90,
    printSpeedMultiplier: 0.75,
    retraction: 1.5,
    notes: "Strong, slightly flexible, water-resistant.",
  },
  {
    id: "abs",
    name: "ABS",
    nozzleTemp: 245,
    bedTemp: 100,
    minNozzleTemp: 230,
    maxNozzleTemp: 260,
    minBedTemp: 90,
    maxBedTemp: 110,
    printSpeedMultiplier: 0.7,
    retraction: 1.0,
    notes: "Enclosure required. Warps. Strong & heat-resistant.",
  },
  {
    id: "asa",
    name: "ASA",
    nozzleTemp: 250,
    bedTemp: 100,
    minNozzleTemp: 235,
    maxNozzleTemp: 265,
    minBedTemp: 90,
    maxBedTemp: 110,
    printSpeedMultiplier: 0.7,
    retraction: 1.0,
    notes: "UV-stable ABS alternative. Outdoor parts.",
  },
  {
    id: "tpu",
    name: "TPU 95A",
    nozzleTemp: 225,
    bedTemp: 50,
    minNozzleTemp: 210,
    maxNozzleTemp: 240,
    minBedTemp: 0,
    maxBedTemp: 60,
    printSpeedMultiplier: 0.4,
    retraction: 0.6,
    notes: "Flexible. Slow. Direct-drive recommended.",
  },
  {
    id: "nylon",
    name: "Nylon (PA)",
    nozzleTemp: 260,
    bedTemp: 80,
    minNozzleTemp: 240,
    maxNozzleTemp: 290,
    minBedTemp: 70,
    maxBedTemp: 100,
    printSpeedMultiplier: 0.65,
    retraction: 2.0,
    notes: "Hygroscopic. Dry filament. Hot enclosure.",
  },
  {
    id: "pc",
    name: "PC (Polycarbonate)",
    nozzleTemp: 270,
    bedTemp: 110,
    minNozzleTemp: 260,
    maxNozzleTemp: 305,
    minBedTemp: 100,
    maxBedTemp: 120,
    printSpeedMultiplier: 0.6,
    retraction: 1.0,
    notes: "Extreme strength. Enclosure mandatory.",
  },
];

export const getPrinter = (id) => PRINTERS.find((p) => p.id === id) || PRINTERS[0];
export const getFilament = (id) => FILAMENTS.find((f) => f.id === id) || FILAMENTS[0];
