// Printer + filament presets. Build volumes are in mm (X x Y x Z where Z is height).
// Sources: manufacturer spec sheets, public OrcaSlicer / PrusaSlicer profile data.

// Multi-color palette used for assigning each scene object to a printer
// extruder/filament when exporting multi-material 3MF. Indices are stable —
// downstream slicers (Bambu Studio, OrcaSlicer) map them to AMS slots 0..7.
export const MULTICOLOR_PALETTE = [
  { name: "White",  hex: "#E5E5E5" },
  { name: "Black",  hex: "#1F1F1F" },
  { name: "Red",    hex: "#E53935" },
  { name: "Green",  hex: "#2E9D57" },
  { name: "Blue",   hex: "#3182CE" },
  { name: "Yellow", hex: "#F0B72E" },
  { name: "Purple", hex: "#7B5CC1" },
  { name: "Orange", hex: "#F97316" },
];


export const PRINTERS = [
  {
    id: "custom",
    brand: "Custom",
    name: "Custom / Generic",
    buildVolume: { x: 220, y: 220, z: 250 },
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 60,
  },
  {
    id: "bambu-p1s",
    brand: "Bambu Lab",
    name: "P1S",
    buildVolume: { x: 256, y: 256, z: 256 },
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 200,
  },
  {
    id: "bambu-a1",
    brand: "Bambu Lab",
    name: "A1",
    buildVolume: { x: 256, y: 256, z: 256 },
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 180,
  },
  {
    id: "bambu-a1-mini",
    brand: "Bambu Lab",
    name: "A1 mini",
    buildVolume: { x: 180, y: 180, z: 180 },
    maxNozzleTemp: 300,
    maxBedTemp: 80,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 180,
  },
  {
    id: "bambu-x1c",
    brand: "Bambu Lab",
    name: "X1 Carbon",
    buildVolume: { x: 256, y: 256, z: 256 },
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 200,
  },
  {
    id: "prusa-mk4",
    brand: "Prusa",
    name: "MK4 / MK4S",
    buildVolume: { x: 250, y: 210, z: 220 },
    maxNozzleTemp: 290,
    maxBedTemp: 120,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 150,
  },
  {
    id: "prusa-mini",
    brand: "Prusa",
    name: "MINI / MINI+",
    buildVolume: { x: 180, y: 180, z: 180 },
    maxNozzleTemp: 280,
    maxBedTemp: 100,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 120,
  },
  {
    id: "prusa-xl",
    brand: "Prusa",
    name: "XL",
    buildVolume: { x: 360, y: 360, z: 360 },
    maxNozzleTemp: 290,
    maxBedTemp: 120,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 200,
  },
  {
    id: "creality-ender3-v3-se",
    brand: "Creality",
    name: "Ender-3 V3 SE",
    buildVolume: { x: 220, y: 220, z: 250 },
    maxNozzleTemp: 260,
    maxBedTemp: 100,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 100,
  },
  {
    id: "creality-ender3-pro",
    brand: "Creality",
    name: "Ender-3 / Pro",
    buildVolume: { x: 220, y: 220, z: 250 },
    maxNozzleTemp: 250,
    maxBedTemp: 100,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 60,
  },
  {
    id: "creality-k1",
    brand: "Creality",
    name: "K1 / K1 Max",
    buildVolume: { x: 220, y: 220, z: 250 },
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 250,
  },
  {
    id: "flashforge-adventurer5m",
    brand: "FlashForge",
    name: "Adventurer 5M / 5M Pro",
    buildVolume: { x: 220, y: 220, z: 220 },
    maxNozzleTemp: 280,
    maxBedTemp: 110,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 200,
  },
  {
    id: "flashforge-ad5x",
    brand: "FlashForge",
    name: "AD5X (Adventurer 5X)",
    buildVolume: { x: 220, y: 220, z: 220 },
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 600,
  },
  {
    id: "flashforge-creator5",
    brand: "FlashForge",
    name: "Creator 5 (IDEX)",
    buildVolume: { x: 300, y: 250, z: 200 },
    maxNozzleTemp: 320,
    maxBedTemp: 120,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 200,
  },
  {
    id: "flashforge-creator5-pro",
    brand: "FlashForge",
    name: "Creator 5 Pro (IDEX)",
    buildVolume: { x: 300, y: 250, z: 200 },
    maxNozzleTemp: 320,
    maxBedTemp: 120,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 200,
  },
  {
    id: "flashforge-creator-pro",
    brand: "FlashForge",
    name: "Creator Pro 2",
    buildVolume: { x: 200, y: 148, z: 150 },
    maxNozzleTemp: 240,
    maxBedTemp: 120,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 60,
  },
  {
    id: "flashforge-finder",
    brand: "FlashForge",
    name: "Finder",
    buildVolume: { x: 140, y: 140, z: 140 },
    maxNozzleTemp: 240,
    maxBedTemp: 0,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 60,
  },
  {
    id: "elegoo-neptune-4",
    brand: "Elegoo",
    name: "Neptune 4",
    buildVolume: { x: 225, y: 225, z: 265 },
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 250,
  },
  {
    id: "elegoo-neptune-4-pro",
    brand: "Elegoo",
    name: "Neptune 4 Pro",
    buildVolume: { x: 225, y: 225, z: 265 },
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 500,
  },
  {
    id: "elegoo-neptune-4-plus",
    brand: "Elegoo",
    name: "Neptune 4 Plus",
    buildVolume: { x: 320, y: 320, z: 385 },
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 500,
  },
  {
    id: "elegoo-neptune-4-max",
    brand: "Elegoo",
    name: "Neptune 4 Max",
    buildVolume: { x: 420, y: 420, z: 480 },
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 500,
  },
  {
    id: "elegoo-neptune-3",
    brand: "Elegoo",
    name: "Neptune 3 / Plus / Pro / Max",
    buildVolume: { x: 220, y: 220, z: 280 },
    maxNozzleTemp: 260,
    maxBedTemp: 110,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 150,
  },
  {
    id: "elegoo-centauri-carbon",
    brand: "Elegoo",
    name: "Centauri Carbon",
    buildVolume: { x: 256, y: 256, z: 256 },
    maxNozzleTemp: 320,
    maxBedTemp: 110,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 500,
  },
  {
    id: "elegoo-orangestorm-giga",
    brand: "Elegoo",
    name: "OrangeStorm Giga",
    buildVolume: { x: 800, y: 800, z: 1000 },
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 200,
  },
  {
    id: "anycubic-kobra2",
    brand: "Anycubic",
    name: "Kobra 2 / Pro / Plus",
    buildVolume: { x: 220, y: 220, z: 250 },
    maxNozzleTemp: 260,
    maxBedTemp: 110,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 150,
  },
  {
    id: "sovol-sv06",
    brand: "Sovol",
    name: "SV06 / SV06 Plus",
    buildVolume: { x: 220, y: 220, z: 250 },
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 100,
  },
  {
    id: "sovol-sv07",
    brand: "Sovol",
    name: "SV07 / SV07 Plus",
    buildVolume: { x: 235, y: 235, z: 300 },
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 250,
  },
  {
    id: "sovol-sv08",
    brand: "Sovol",
    name: "SV08",
    buildVolume: { x: 350, y: 350, z: 345 },
    maxNozzleTemp: 300,
    maxBedTemp: 120,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 500,
  },
  {
    id: "voron-2.4",
    brand: "Voron",
    name: "Voron 2.4 (300mm)",
    buildVolume: { x: 300, y: 300, z: 300 },
    maxNozzleTemp: 300,
    maxBedTemp: 120,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 200,
  },
  // FLSUN — delta-style kinematics. `buildVolume.x/y` here is the
  // BOUNDING BOX of the circular bed (i.e., diameter × diameter)
  // because ForgeSlicer's "fits on plate" check uses an axis-
  // aligned bbox. The `kinematics: "delta"` flag drives the
  // viewport's round build-plate render (iter-100.6). The polygon-
  // accurate circle for OrcaSlicer staging lives in
  // `lib/orcaProfiles.js`.
  // Specs cross-checked against flsun3d.com product pages and
  // OrcaSlicer's bundled FLSun profiles.
  {
    id: "flsun-q5",
    brand: "FLSUN",
    name: "Q5 (delta)",
    kinematics: "delta",
    buildVolume: { x: 200, y: 200, z: 200 },
    maxNozzleTemp: 260,
    maxBedTemp: 100,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 100,
  },
  {
    id: "flsun-sr",
    brand: "FLSUN",
    name: "Super Racer (SR)",
    kinematics: "delta",
    buildVolume: { x: 260, y: 260, z: 330 },
    maxNozzleTemp: 260,
    maxBedTemp: 110,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 200,
  },
  {
    id: "flsun-v400",
    brand: "FLSUN",
    name: "V400",
    kinematics: "delta",
    buildVolume: { x: 300, y: 300, z: 410 },
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 400,
  },
  {
    id: "flsun-t1-pro",
    brand: "FLSUN",
    name: "T1 Pro",
    kinematics: "delta",
    buildVolume: { x: 260, y: 260, z: 330 },
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 600,
  },
  {
    id: "flsun-s1",
    brand: "FLSUN",
    name: "S1 (Pro)",
    kinematics: "delta",
    buildVolume: { x: 260, y: 260, z: 330 },
    maxNozzleTemp: 350,
    maxBedTemp: 110,
    defaultNozzle: 0.4,
    defaultPrintSpeed: 1200,
  },
];

export const FILAMENTS = [
  {
    id: "pla",
    name: "PLA",
    nozzleTemp: 210,
    bedTemp: 60,
    minNozzleTemp: 190,
    maxNozzleTemp: 230,
    minBedTemp: 0,
    maxBedTemp: 70,
    printSpeedMultiplier: 1.0,
    retraction: 1.0,
    notes: "Easy. Great for prototyping. No enclosure needed.",
  },
  {
    id: "pla-plus",
    name: "PLA+",
    nozzleTemp: 215,
    bedTemp: 60,
    minNozzleTemp: 200,
    maxNozzleTemp: 235,
    minBedTemp: 0,
    maxBedTemp: 70,
    printSpeedMultiplier: 1.0,
    retraction: 1.0,
    notes: "Tougher than PLA, same workflow.",
  },
  {
    id: "petg",
    name: "PETG",
    nozzleTemp: 240,
    bedTemp: 80,
    minNozzleTemp: 220,
    maxNozzleTemp: 260,
    minBedTemp: 70,
    maxBedTemp: 90,
    printSpeedMultiplier: 0.75,
    retraction: 1.5,
    notes: "Strong, slightly flexible, water-resistant.",
  },
  {
    id: "abs",
    name: "ABS",
    nozzleTemp: 245,
    bedTemp: 100,
    minNozzleTemp: 230,
    maxNozzleTemp: 260,
    minBedTemp: 90,
    maxBedTemp: 110,
    printSpeedMultiplier: 0.7,
    retraction: 1.0,
    notes: "Enclosure required. Warps. Strong & heat-resistant.",
  },
  {
    id: "asa",
    name: "ASA",
    nozzleTemp: 250,
    bedTemp: 100,
    minNozzleTemp: 235,
    maxNozzleTemp: 265,
    minBedTemp: 90,
    maxBedTemp: 110,
    printSpeedMultiplier: 0.7,
    retraction: 1.0,
    notes: "UV-stable ABS alternative. Outdoor parts.",
  },
  {
    id: "tpu",
    name: "TPU 95A",
    nozzleTemp: 225,
    bedTemp: 50,
    minNozzleTemp: 210,
    maxNozzleTemp: 240,
    minBedTemp: 0,
    maxBedTemp: 60,
    printSpeedMultiplier: 0.4,
    retraction: 0.6,
    notes: "Flexible. Slow. Direct-drive recommended.",
  },
  {
    id: "nylon",
    name: "Nylon (PA)",
    nozzleTemp: 260,
    bedTemp: 80,
    minNozzleTemp: 240,
    maxNozzleTemp: 290,
    minBedTemp: 70,
    maxBedTemp: 100,
    printSpeedMultiplier: 0.65,
    retraction: 2.0,
    notes: "Hygroscopic. Dry filament. Hot enclosure.",
  },
  {
    id: "pc",
    name: "PC (Polycarbonate)",
    nozzleTemp: 270,
    bedTemp: 110,
    minNozzleTemp: 260,
    maxNozzleTemp: 305,
    minBedTemp: 100,
    maxBedTemp: 120,
    printSpeedMultiplier: 0.6,
    retraction: 1.0,
    notes: "Extreme strength. Enclosure mandatory.",
  },
];

export const getPrinter = (id) => PRINTERS.find((p) => p.id === id) || PRINTERS[0];
export const getFilament = (id) => FILAMENTS.find((f) => f.id === id) || FILAMENTS[0];

// ---------- Slicer software directory ----------
// Each slicer is an installable desktop program that opens .3mf/.stl files.
// We list the printer-vendor's native slicer first, then OrcaSlicer & PrusaSlicer
// as widely-compatible community options when relevant.
export const SLICERS = {
  orca:    { id: "orca",    name: "OrcaSlicer",            url: "https://github.com/SoftFever/OrcaSlicer/releases", formats: ["3mf", "stl"] },
  prusa:   { id: "prusa",   name: "PrusaSlicer",           url: "https://www.prusa3d.com/page/prusaslicer_424/",     formats: ["3mf", "stl"] },
  bambu:   { id: "bambu",   name: "Bambu Studio",          url: "https://bambulab.com/en/download/studio",            formats: ["3mf", "stl"] },
  flashprint: { id: "flashprint", name: "Flash Studio Desktop", url: "https://www.flashforge.com/pages/download", formats: ["3mf", "stl"] },
  orca_ff: { id: "orca_ff", name: "Orca-Flashforge",          url: "https://github.com/Flashforge-official/OrcaSlicer-Flashforge/releases", formats: ["3mf", "stl"] },
  creality_print: { id: "creality_print", name: "Creality Print", url: "https://www.crealitycloud.com/software-firmware/software", formats: ["3mf", "stl"] },
  elegoo:  { id: "elegoo",  name: "Elegoo Slicer",         url: "https://www.elegoo.com/pages/3d-printing-user-center", formats: ["3mf", "stl"] },
  cura:    { id: "cura",    name: "UltiMaker Cura",        url: "https://ultimaker.com/software/ultimaker-cura/",      formats: ["3mf", "stl"] },
  superslicer: { id: "superslicer", name: "SuperSlicer",   url: "https://github.com/supermerill/SuperSlicer/releases", formats: ["3mf", "stl"] },
};

// Per-printer slicer recommendations. First entry is the printer-maker's default.
// Falls back to a vendor-agnostic list when the printer isn't in this map.
export const PRINTER_SLICERS = {
  // Bambu
  "bambu-p1s":      ["bambu", "orca"],
  "bambu-a1":       ["bambu", "orca"],
  "bambu-a1-mini":  ["bambu", "orca"],
  "bambu-x1c":      ["bambu", "orca"],
  // Prusa
  "prusa-mk4":      ["prusa", "orca", "superslicer"],
  "prusa-mini":     ["prusa", "orca", "superslicer"],
  "prusa-xl":       ["prusa", "orca", "superslicer"],
  // Creality
  "creality-ender3-v3-se": ["creality_print", "orca", "cura"],
  "creality-ender3-pro":   ["creality_print", "cura", "orca"],
  "creality-k1":           ["creality_print", "orca"],
  // FlashForge
  "flashforge-adventurer5m": ["flashprint", "orca_ff", "orca"],
  "flashforge-ad5x":         ["flashprint", "orca_ff", "orca"],
  "flashforge-creator5":     ["flashprint", "orca_ff"],
  "flashforge-creator5-pro": ["flashprint", "orca_ff"],
  "flashforge-creator-pro":  ["flashprint", "cura"],
  "flashforge-finder":       ["flashprint"],
  // Elegoo
  "elegoo-neptune-4":       ["elegoo", "cura", "orca"],
  "elegoo-neptune-4-pro":   ["elegoo", "cura", "orca"],
  "elegoo-neptune-4-plus":  ["elegoo", "cura", "orca"],
  "elegoo-neptune-4-max":   ["elegoo", "cura", "orca"],
  "elegoo-neptune-3":       ["elegoo", "cura", "orca"],
  "elegoo-centauri-carbon": ["elegoo", "orca"],
  "elegoo-orangestorm-giga":["elegoo", "cura"],
  // Anycubic
  "anycubic-kobra2":        ["orca", "cura"],
  // Sovol
  "sovol-sv06":             ["orca", "prusa", "superslicer"],
  "sovol-sv07":             ["orca", "prusa", "cura"],
  "sovol-sv08":             ["orca", "prusa"],
  // Voron
  "voron-2.4":              ["superslicer", "orca", "prusa"],
  // Custom / fallback
  "custom":                 ["orca", "prusa", "cura"],
};

export function getSlicersForPrinter(printerId) {
  const ids = PRINTER_SLICERS[printerId] || ["orca", "prusa"];
  return ids.map((id) => SLICERS[id]).filter(Boolean);
}
